[[certification]]
=== Certification
include::includes/header.adoc[]

A natural progression from the Primed program is Certification. 
Red Hat Container Certification is available for software vendors that offer commercial 
applications packaged and distributed as containers. The certification process is intended to help ensure that applications are 
built and packaged according to Red Hat's enterprise standards. 

In addition to the practices outlined under <<integration#recommended-practices, recommended practices>>, software vendors should ensure that their containers meet the following requirements.

* Images should contain a directory named `/licenses` that holds all relevant licensing information.
** End users should be aware of the terms and conditions applicable to the image.
* Image dockerfiles should contain the following labels:
** name
** vendor
** version
** release
* Images should contain a help file as outlined http://docs.projectatomic.io/container-best-practices/#_creating_a_help_file[here].
* Images should have a tag other than latest so that they can be uniquely identified. 

The policy describing these standards can be found https://connect.redhat.com/zones/containers/container-certification-policy-guide#good_layer_count[here].
Red Hat Partner Engineering mantains an example Dockerfile https://github.com/RHsyseng/container-rhel-examples/blob/master/starter/Dockerfile[here] which hits all the basic requirements for certification.
