[[operator-framework]]
== Operator Framework
include::includes/header.adoc[]

An Operator is an application-specific controller that extends the Kubernetes 
API to create, configure, and manage instances of complex stateful applications 
on behalf of a Kubernetes user. It builds upon the basic Kubernetes resource and
controller concepts but includes domain or application-specific knowledge to 
automate common tasks. 

The Operator Framework 
(https://coreos.com/blog/introducing-operator-framework[intro blog post]) is an 
open source toolkit to manage Kubernetes native applications, called Operators, 
in an effective, automated, and scalable way. Operators take advantage of 
Kubernetes's extensibility to deliver the automation advantages of cloud 
services like provisioning, scaling, and backup/restore while being able to run 
anywhere that Kubernetes can run.

This guide shows how to build a simple Memcached Operator and how to manage its 
lifecycle from install to update to a new version. For that, we will use two 
center pieces of the framework:

* <<operator_sdk>>
* <<operator_lifecycle_manager>>

[NOTE]
====
Requirements: Please make sure that the Operator SDK is installed on the 
development machine. Additionally, the Operator Lifecycle Manager must be 
installed in the cluster (1.8 or above to support the apps/v1beta2 API group) 
before running this guide.
====

[[operator_sdk]]
=== Build an Operator using the Operator SDK

The Operator SDK makes it easier to build Kubernetes native applications, a 
process that can require deep, application-specific operational knowledge. 
The SDK not only lowers that barrier, but it also helps reduce the amount of 
boilerplate code needed for many common management capabilities, such as 
metering or monitoring. Moreover ,it Allows your developers to build an Operator
based on your expertise without requiring knowledge of Kubernetes API 
complexities.

This section walks through an example of building a simple Memcached Operator 
using tools and libraries provided by the Operator SDK.

[NOTE]
====
Requirements: Please make sure that the 
https://github.com/operator-framework/operator-sdk[Operator SDK],
https://kubernetes.io/docs/tasks/tools/install-kubectl/[Kubernetes-cli]
and the https://golang.org/doc/install[Go Programming Language] are installed.
Furthermore, make sure that the GOPATH is setup.
====

*_Create a new project_*

Use the CLI to create a new memcached-operator project:

----
$ cd $GOPATH/src/github.com/example-inc/
$ operator-sdk new memcached-operator --api-version=cache.example.com/v1alpha1 --kind=Memcached
$ cd memcached-operator
----

This creates the memcached-operator project specifically for watching the 
Memcached resource with APIVersion = cache.example.com/v1apha1 and Kind = 
Memcached.

[NOTE]
====
Learn more about the project directory structure from the SDK 
https://github.com/operator-framework/operator-sdk/blob/master/doc/project_layout.md[project layout]
documentation.
====

*_Customize the Operator logic_*

For this example, the Memcached Operator will execute the following reconciliation logic for each Memcached custom resource:

* Create a Memcached Deployment if it doesn't exist
* Ensure that the Deployment size is the same as specified by the Memcached 
CustomResource (CR) spec
* Update the Memcached CR status with the names of the memcached pods

*_Watch for the Memcached custom resource definition_*

By default, the memcached-operator watches Memcached resource events as shown in
cmd/memcached-operator/main.go.

----
func main() {
  sdk.Watch("cache.example.com/v1alpha1", "Memcached", "default", 5)
  sdk.Handle(stub.NewHandler())
  sdk.Run(context.TODO())
}
----

*_Define the Memcached spec and status_*

Modify the spec and status of the Memcached CRD at pkg/apis/cache/v1alpha1/
types.go:

----
type MemcachedSpec struct {
	// Size is the size of the memcached deployment
	Size int32 `json:"size"`
}
type MemcachedStatus struct {
	// Nodes are the names of the memcached pods
	Nodes []string `json:"nodes"`
}
----

Update the generated code for the CR:

----
$ cd $GOPATH/src/github.com/example-inc/
$ cd memcached-operator
$ operator-sdk generate k8s
----

*_Define the Handler_*

The reconciliation loop for an event is defined in the Handle() function at 
pkg/stub/handler.go.

Replace this file with the reference implementation found 
https://github.com/operator-framework/getting-started/blob/master/handler.go.tmpl#L7[here]. 
You will need to update the highlighted line if you have changed the import path
of this project to something other than “example-inc”.

[NOTE]
====
Update: Update the code you just replaced with the updated code
https://github.com/operator-framework/operator-sdk/commit/34c317ef90e63a5e4d6ed29ca1826ee32b16f112#diff-7bcd1b78beaf078c430fa8d1fcc8ef2e[here].
====

[NOTE]
====
Note: The provided handler implementation is only meant to demonstrate the use 
of the SDK APIs and is not representative of the best practices of a 
reconciliation loop.
====

*_Build and run the Operator_*

Build the memcached-operator image and push it to a registry. Please make sure 
you have a an account on Quay.io for the next step, or substitute your 
preferred container registry. 
On the registry, https://quay.io/new/[create a new public image] repository 
named “memcached-operator”.

----
$ cd $GOPATH/src/github.com/example-inc/
$ cd memcached-operator
$ operator-sdk build quay.io/example/memcached-operator:v0.0.1
$ docker push quay.io/example/memcached-operator:v0.0.1
----

Kubernetes deployment manifests are generated in deploy/operator.yaml. The 
deployment image is set to the container image specified above.

*_Deploy the Memcached Operator_*

----
$ kubectl create -f deploy/rbac.yaml
$ kubectl create -f deploy/crd.yaml
$ kubectl create -f deploy/operator.yaml
----

*_Verify that the Operator is running_*

----
$ kubectl get pods
NAME                                  READY     STATUS    RESTARTS   AGE
memcached-operator-75c4b4c665-8jnj5   1/1       Running   0          20s
----

*_Clean up_*

----
$ kubectl delete -f deploy/operator.yaml
$ kubectl delete -f deploy/rbac.yaml
----

[[operator_lifecycle_manager]]
=== Manage the Operator using the Operator Lifecycle Manager


